// Code generated by sqlc. DO NOT EDIT.
// source: auth.sql

package entity

import (
	"context"
)

const comparePassword = `-- name: ComparePassword :one
SELECT compare_password($1, $2)
`

type ComparePasswordParams struct {
	Plaintext string `json:"plaintext"`
	Encrypted string `json:"encrypted"`
}

func (q *Queries) ComparePassword(ctx context.Context, arg ComparePasswordParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, comparePassword, arg.Plaintext, arg.Encrypted)
	var compare_password bool
	err := row.Scan(&compare_password)
	return compare_password, err
}
